### ISSUE TITLE
amazon ses error while sending email MessageRejected

### ISSUE THREAD

**Issue by way2enjoy2** [okamos/php-ses#10]
i am trying to send message with this code but it gives error
can u plz tell where i am doing mistake

require 'autoload.php';

require 'src/ses.php';

$ses = new SimpleEmailService(
    'xxxxxxxxx',
    'xxxxxxxxxxxx', 
    'us-east-1' 
);

$envelope = new SimpleEmailServiceEnvelope(
    'noreply@xxxxxxxx.com',
    'This is test email',
    'Hello how are you. this is test email'
);

$envelope->addTo('ffffff@hhhhh.com');

$requestId = $ses->sendEmail($envelope);

var_dump($requestId);

**Comment by okamos** [comment]
@way2enjoy2 Could you write the error message and stack trace?

**Comment by way2enjoy2** [comment]
object(SimpleEmailServiceError)#30 (2) { ["code"]=> string(15) "MessageRejected" ["description"]=> string(134) "Indicates that the action failed, and the message could not be sent. Check the error stack for a description of what caused the error." } 

how to get the stack trace ??

**Comment by okamos** [comment]
@way2enjoy2 Sorry, this library wraps AWS error messages. I will add more information if error.
I guess your email noreply@YOURDOMAIN is not verified.
Please check the document https://aws.amazon.com/premiumsupport/knowledge-center/ses-554-400-message-rejected-error/

**Comment by way2enjoy2** [comment]
its verified aws shows green and above all it is more than 2 days we got verification. can u plz add sample code which we people can use

**Comment by way2enjoy2** [comment]
its working. i had wrong region given
