### ISSUE TITLE
Bad Request sending attachments

### ISSUE THREAD

**Issue by CodeCommerce** [okamos/php-ses#2]
Hi - i have a Problem by sending Mails with Attachments.

If i remove line 299 in file ses-envelope.php - i receive an empty file on my mail.
`$raw_message .= "\n" . chunk_split(base64_encode($attachment['data']), 76, "\n") . "\n";`
If i let line 299 in the code - i'll get a request error

object(GuzzleHttp\Psr7\Response)[29]
  private 'reasonPhrase' => string 'Bad Request' (length=11)
  private 'statusCode' => int 400

May u have an idea how to fix this.
Didn't find anything and tried a bit to change this line of code.

Thanks

**Comment by okamos** [comment]
Hi, @CodeCommerce sorry for my late reply.

I'll fix it.
Please wait for the update.

**Comment by okamos** [comment]
Hi @CodeCommerce 
I fixed sending email with attachments. in https://github.com/okamos/php-ses/commit/d13b172ed3bb7b9b51ea3eb3c8b8c2205bdf91fa

Bad request was caused by limit on query parameter with GET request.
Please you'll try it later.
Sincerely.
