### ISSUE TITLE
ses.php parse error

### ISSUE THREAD

**Issue by buttakbar** [okamos/php-ses#6]
Please remove trailing comma from php-ses/src/se.php line#406

**Comment by okamos** [comment]
@buttakbar Hi, thanks for open this issue.
I fixed in https://github.com/okamos/php-ses/commit/50d52993ff27e4d2dd4e47cc164edfacf9763326.
But I forgot release this commit.
Please use `composer require okamos/php-ses:1.0.4` .

**Comment by buttakbar** [comment]
Hi

Now I am getting the following error:

$ composer require okamos/php-ses
Content-Length mismatch, received 15656 bytes out of the expected 604113
http://repo.packagist.org could not be fully loaded, package information
was loaded from the local cache and may be out of date

$ composer require okamos/php-ses:1.0.4
Content-Length mismatch, received 21256 bytes out of the expected 604113
http://repo.packagist.org could not be fully loaded, package information
was loaded from the local cache and may be out of date



Thanks
Akbar

**Comment by okamos** [comment]
@buttakbar Hi

It seems to be due to composer settings or local cache.
Please try to [Edit settings](https://stackoverflow.com/questions/38635257/composer-content-length-mismatch) or `composer clear-cache`

**Comment by buttakbar** [comment]
Hi

Ok, I will try it and update you about it.

Thanks
Albar

**Comment by buttakbar** [comment]
Hi

I have updated the config file of my system and It works.

Thanks
Akbar
