### ISSUE TITLE
Library is not working with php 7.0.9 version

### ISSUE THREAD

**Issue by sam1238801** [okamos/php-ses#8]
Hello,

Php-ses Library is not working with php 7.0.9 version.

I am getting the below fatal error:

Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.2.5". You are running 7.0.9. in /opt/lampp/htdocs/email/vendor/composer/platform_check.php on line 24

Please help me out.

**Comment by okamos** [comment]
Hello, @sam1238801-san

php-ses version 7.x support PHP version >= 7.2 only.
Please use 1.x with php 7.0.9

like below in composer.json
```json
"require": {
  "okamos/php-ses": "^1.0"
}
```

Close this issue if resolved
